### ISSUE TITLE
InvalidWireTypeException when attempting to use with Bazel

### ISSUE THREAD

**Issue by Nickersoft** [scalapb/zio-grpc#255]
Hey folks, I've been trying to adapt `zio-grpc` for my Bazel project using [rules_scala](https://github.com/bazelbuild/rules_scala)'s custom code generator support. 

However, attempting to compile my code throws:

```
com.google.protobuf.InvalidProtocolBufferException$InvalidWireTypeException: Protocol message tag had invalid wire type.
        at com.google.protobuf.InvalidProtocolBufferException.invalidWireType(InvalidProtocolBufferException.java:111)
        at com.google.protobuf.UnknownFieldSet$Builder.mergeFieldFrom(UnknownFieldSet.java:557)
        at com.google.protobuf.GeneratedMessageV3.parseUnknownField(GeneratedMessageV3.java:320)
        at com.google.protobuf.compiler.PluginProtos$CodeGeneratorRequest.<init>(PluginProtos.java:1092)
        at com.google.protobuf.compiler.PluginProtos$CodeGeneratorRequest.<init>(PluginProtos.java:1008)
        at com.google.protobuf.compiler.PluginProtos$CodeGeneratorRequest$1.parsePartialFrom(PluginProtos.java:2313)
        at com.google.protobuf.compiler.PluginProtos$CodeGeneratorRequest$1.parsePartialFrom(PluginProtos.java:2307)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:86)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:48)
        at com.google.protobuf.GeneratedMessageV3.parseWithIOException(GeneratedMessageV3.java:366)
        at com.google.protobuf.compiler.PluginProtos$CodeGeneratorRequest.parseFrom(PluginProtos.java:1467)
        at protocgen.CodeGenApp.run(CodeGenApp.scala:44)
        at protocgen.CodeGenApp.run$(CodeGenApp.scala:39)
        at scalapb.zio_grpc.ZioCodeGenerator$.run(ZioCodeGenerator.scala:21)
        at protocgen.CodeGenApp.main(CodeGenApp.scala:27)
        at protocgen.CodeGenApp.main$(CodeGenApp.scala:26)
        at scalapb.zio_grpc.ZioCodeGenerator$.main(ZioCodeGenerator.scala:21)
        at scalapb.zio_grpc.ZioCodeGenerator.main(ZioCodeGenerator.scala)
```

To use the generator, I'm just importing the codegen as a Maven library then wrapping it as a codegen for Bazel:

```python
scala_binary(
    name = "codegen",
    deps = ["@maven//:com_thesamet_scalapb_zio_grpc_zio_grpc_codegen_2_12"],
    main_class = "scalapb.zio_grpc.ZioCodeGenerator"
)

scala_proto_toolchain(
    name = "scala_proto_toolchain",
    with_grpc = True,
    code_generator = ":codegen",
    visibility = ["//visibility:public"],
)

toolchain(
    name = "scalapb_toolchain",
    toolchain = ":scala_proto_toolchain",
    toolchain_type = "@io_bazel_rules_scala//scala_proto:toolchain_type",
    visibility = ["//visibility:public"],
)
```

`scala_proto_library` uses ScalaPB under-the-hood so I assumed integration would be rather seamless. I'm not sure if maybe this issue is being caused by a dependency incompatibility or a missing dependency or something? I tried digging in myself but am not super familiar with how custom protobuf generators work. Interestingly enough, removing `with_grpc = True` throws a different error:

```
com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
        at com.google.protobuf.InvalidProtocolBufferException.invalidTag(InvalidProtocolBufferException.java:102)
        at com.google.protobuf.CodedInputStream$StreamDecoder.readTag(CodedInputStream.java:2068)
```

so it definitely seems like some sort of binary encoding incompatibility. I tried to cross-check the ScalaPB version between this repo and `rules_scala` but couldn't figure out which compiler version this library depends on. `rules_scala` uses compilerplugin v0.9.7.

I'm happy to open an issue on their side too, but figured I'd start here seeing it seems to be an error thrown specifically from this library.

**Comment by Nickersoft** [comment]
Hey @thesamet, thanks for the quick reply! I imagined as much... and like you, I'm not entirely certain how the toolchain works either. I've posted an additional ticket over on that repo to see if there's any additional insight from the rule maintainers.

**Comment by Nickersoft** [comment]
This issue has been resolved in the linked ticket. Thanks for the guidance!
