### ISSUE TITLE
ZService.withMetadata not thread safe

### ISSUE THREAD

**Issue by ollyw** [scalapb/zio-grpc#270]
When testing concurrent calls to a ZService the service started throwing exceptions. The ZService works fine without concurrency. An example exception is:
```
Status{code=INTERNAL, description=Index 4 out of bounds for length 4, cause=java.lang.ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 4
	at io.grpc.Metadata.serialize(Metadata.java:470)
	at io.grpc.InternalMetadata.serialize(InternalMetadata.java:78)
	at io.grpc.internal.TransportFrameUtil.toHttp2Headers(TransportFrameUtil.java:51)
	at io.grpc.netty.Utils.convertClientHeaders(Utils.java:222)
	at io.grpc.netty.NettyClientStream$Sink.writeHeadersInternal(NettyClientStream.java:145)
	at io.grpc.netty.NettyClientStream$Sink.writeHeaders(NettyClientStream.java:121)
	at io.grpc.internal.AbstractClientStream.start(AbstractClientStream.java:159)
	at io.grpc.internal.ForwardingClientStream.start(ForwardingClientStream.java:92)
	at io.grpc.internal.InternalSubchannel$CallTracingTransport$1.start(InternalSubchannel.java:681)
	at io.grpc.internal.ClientCallImpl.startInternal(ClientCallImpl.java:283)
	at io.grpc.internal.ClientCallImpl.start(ClientCallImpl.java:188)
	at scalapb.zio_grpc.client.ZClientCallImpl$.$anonfun$start$extension$1(ZClientCall.scala:48)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at zio.internal.FiberContext.evaluateNow(FiberContext.scala:490)
	at zio.internal.FiberContext.$anonfun$evaluateLater$1(FiberContext.scala:776)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
}
```

Looking at the underlying Java API, the headers are not threadsafe. From the docs in ClientCall.start
```
Since Metadata is not thread-safe, the caller must not access (read or write) headers after this point.
```
Therefore it seems that the headers should be created _per call_ not per ZService. My usage of the service was using ZService ` withMetadata(headers: scalapb.zio_grpc.SafeMetadata): ZService[R, Any] ` method. Changing the app to use `withMetadataM` and have an effect create new headers each time works fine without any concurrency issues.

I can't see how the `withMetadata` method would ever be safe because the `SafeMetadata` would be changed by concurrent calls. It could be modified to be a call by name `withMetadata(headers: => scalapb.zio_grpc.SafeMetadata): ZService[R, Any] `, but I am not sure this is enough of an indication to the user that the headers are created for each call, not once for all calls. Perhaps something like `withMetadata(perCallHeaders: () => scalapb.zio_grpc.SafeMetadata): ZService[R, Any] ` would work, but the question is, does the effectless `withMetadata` need to even exist?

P.S. Thanks for the library. It is awesome :1st_place_medal:

**Comment by thesamet** [comment]
You are right! I think it would be sufficient to have `withMetadata` take the metadata by-name. I wouldn't go as far as taking unit or removing it, for ergonomic reasons. A PR will be welcome! (would need docs/examples to be looked at too)

**Comment by ollyw** [comment]
Sorry about the delay at looking into this. I just took a look now and attempted to rework withMetadata to take a by name parameter, but it still wouldn't be safe because SafeMetadata can only be constructed with an effect, and therefore there is no way to construct a new SafeMetadata per call in a by name variant of withMetadata.

If SafeMetadata had an effectless constructor, it could work, but SafeMetdata includes a semaphone, so this wouldn't be possible. An alternative for this would be to pass a Metadata, not a SafeMetadata, which would require withMetadata to return an effect, which complicates things further and makes the builder pattern methods with* inconsistent.

Can you see another way, or are you happy to remove? I put in a PR to remove if you are happy

**Comment by thesamet** [comment]
Thanks for reporting and nvestigating this issue, as well as sending a PR to prevent others from running into this problem. Merged!
